# Generated by Django 3.1.2 on 2021-02-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, default='NA', max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('country_of_residence', models.CharField(blank=True, default='NA', max_length=30)),
                ('contact_number', models.CharField(blank=True, default='NA', max_length=20)),
                ('willingness_to_join_session', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'May be')], default='NA', max_length=10)),
                ('comments', models.TextField(blank=True, default='None')),
                ('registered_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
